import Image from '../../assets/images/User.svg';

export const CardArray = [
  {
    imageCard: Image,
    Author: 'Julio Nunes Avelar',
    Avaliation: 1,
    Curse: 'Matemática para OMU',
    Stars: 1,
    id: 89,
    link: '#',
  },
  {
    imageCard: Image,
    Author: 'Bhryan Stepenhen da Cruz',
    Avaliation: 2,
    Curse: 'Programação para OBI',
    Stars: 2,
    id: 90,
    link: '#',
  },
  {
    imageCard: Image,
    Author: 'Diego',
    Avaliation: 3,
    Curse: 'Prgraming For Web',
    Stars: 3,
    id: 91,
    link: '#',
  },
  {
    imageCard: Image,
    Author: 'Rocket',
    Avaliation: 4,
    Curse: 'Starter',
    Stars: 4,
    id: 92,
    link: '#',
  },
  {
    imageCard: Image,
    Author: 'Mayk',
    Avaliation: 5,
    Curse: 'Root',
    Stars: 5,
    id: 93,
    link: '#',
  },
  {
    imageCard: Image,
    Author: 'Akita',
    Avaliation: 6,
    Curse: 'History Computer',
    Stars: 1,
    id: 94,
    link: '#',
  },
  {
    imageCard: Image,
    Author: 'React',
    Avaliation: 6,
    Curse: 'Reactjs',
    Stars: 2,
    id: 95,
    link: '#',
  },
  {
    imageCard: Image,
    Author: 'Podemos',
    Avaliation: 7,
    Curse: 'math base',
    Stars: 3,
    id: 96,
    link: '#',
  },
  {
    imageCard: Image,
    Author: 'Code coffe',
    Avaliation: 8,
    Curse: 'low code',
    Stars: 4,
    id: 97,
    link: '#',
  },
];
